// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** Direct Supabase (local dev). */
const SUPABASE_DIRECT_URL = "https://lqffeyniustvyegcigyy.supabase.co";
/** Cloudflare-proxied Supabase (production — db.sageteach.top → project host). */
const SUPABASE_PROXY_URL = "https://db.sageteach.top";

const supabaseUrl = import.meta.env.PROD ? SUPABASE_PROXY_URL : SUPABASE_DIRECT_URL;

const supabaseKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY?.trim() ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

if (!supabaseKey) {
  const message =
    "Missing VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY.";
  console.error(`[Supabase] ${message}`);
  throw new Error(message);
}

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: "sage-auth",
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    detectSessionInUrl: true,
  },
});
